import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import ReactQueryProvider from './react-query-provider'

const poppins = Poppins({ weight: ['400', '500'], subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Thullo',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<ReactQueryProvider>{children}</ReactQueryProvider>
			</body>
		</html>
	)
}
